### PR TITLE
generate .css resource from Sass each time hugo builds

### PR DESCRIPTION
**Pull request by mikesteele81**
This change causes hugo to generate a new styles.css file each time the site builds. As a result, the hugo extended version will be needed. I compared the version of styles.css you had to the one that hugo generates, and they appear to be the same other than whitespace and number padding.

### CODE REVIEW

**Comment by gevhaz** [comment]
This seems really convenient. I faced the troubles with forgetting to rebuild the CSS separately from the site myself many times.

I want as many people as possible to be able to use the theme out of the box. But it seems the extended version is what you get when you install Hugo through both Ubuntu's and Arch Linux's package managers so perhaps it will simply work for the majority of people. Could you add to the README that the extended version is required though? And perhaps what needs to be done if you don't have it? It seems that Dart can be used without the extended version, so maybe link to here: https://gohugo.io/hugo-pipes/transpile-sass-to-css/#usage

**Comment by mikesteele81** [comment]
Okay, I'll add something in the README. This is something Windows users might run into if they don't know there are separate variants of hugo since the "extended" installer is towards the bottom of the list of download options.

Regarding Dart Sass, we would still need hugo extended to get this working as far as I know because Hugo's pipes feature is part of extended.

**Comment by mikesteele81** [comment]
correction: I see that the extended version is not needed in order to use Dart Sass.

**Review by gevhaz — APPROVED** [review]

**Comment by gevhaz** [comment]
Sorry for the wait. I moved and adjusted the documentation a bit, but other than that I'm merging as is. Thanks for the contribution :)

**Pull request merged**
